version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: demo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # ホストとコンテナのポートをマッピング
    volumes:
      - db_data:/var/lib/mysql # 永続データ保存

volumes:
  db_data:
